/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_rg_androidstudiodemo_jni_MathKit */

#ifndef _Included_com_example_rg_androidstudiodemo_jni_MathKit
#define _Included_com_example_rg_androidstudiodemo_jni_MathKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_rg_androidstudiodemo_jni_MathKit
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_rg_androidstudiodemo_jni_MathKit_square
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
